apiVersion: apps/v1
kind: Deployment
metadata:
  name: brokerone-kafka-local
  namespace: kafka-local
  labels:
    app: brokerone-kafka-local
    app.kubernetes.io/name: brokerone-kafka-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brokerone-kafka-local
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: brokerone-kafka-local
        app.kubernetes.io/name: brokerone-kafka-local
    spec:
      serviceAccountName: kafka-job-creator
      terminationGracePeriodSeconds: 150
      containers:
        - name: brokerone-kafka-local
          image: brokerone-kafka:local
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]
          envFrom:
            - secretRef:
                name: brokerone-kafka-local-env
          resources:
            requests:
              cpu: "100m"
              memory: "300Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: supervisor-kafa-config
              mountPath: /etc/supervisor/conf.d/supervisord.conf
              subPath: supervisord.conf
      volumes:
        - name: supervisor-kafa-config
          configMap:
            name: supervisor-kafa-config