apiVersion: v1
kind: Secret
metadata:
  name: keda-kafka-secrets
  namespace: kafka-local
type: Opaque
stringData:
  # Exemplos comuns:
  # sasl: plaintext
  # sasl: scram_sha512
  # tls: enable
  sasl: plaintext
  username: kafka
  password: troque-aqui
  tls: disable
