apiVersion: v1
kind: ConfigMap
metadata:
  name: supervisor-kafa-config
  namespace: kafka-local
data:
  supervisord.conf: |
    [supervisord]
    logfile=/dev/null
    loglevel=info
    pidfile=/tmp/supervisord.pid
    nodaemon=false
    minfds=1024
    minprocs=200

    [rpcinterface:supervisor]
    supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

    [supervisorctl]
    serverurl=unix:///tmp/supervisor.sock

    [program:laravel-worker]
    process_name=%(program_name)s_%(process_num)02d
    command=php /app/broker-api/artisan kafka:start
    autostart=true
    autorestart=true
    user=root
    numprocs=1
    redirect_stderr=true
    stdout_logfile=/dev/stdout
    stopwaitsecs=120
    stdout_logfile_maxbytes=0